// <auto-generated />
using System;
using HW6_module4;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW6_module4.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20230810221149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtistSong", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("ArtistId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("ArtistSong");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            SongId = 2
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 4
                        },
                        new
                        {
                            ArtistId = 2,
                            SongId = 5
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 4
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 2
                        },
                        new
                        {
                            ArtistId = 5,
                            SongId = 1
                        });
                });

            modelBuilder.Entity("HW6_module4.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeteofBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeteofBirth");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InstagramUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeteofBirth = new DateTime(1996, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivavivanov@gmail.com",
                            InstagramUrl = "vaviva1122",
                            Name = "Ivan"
                        },
                        new
                        {
                            Id = 2,
                            DeteofBirth = new DateTime(1997, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Petrvanov@gmail.com",
                            InstagramUrl = "Petr1122",
                            Name = "Petr"
                        },
                        new
                        {
                            Id = 3,
                            DeteofBirth = new DateTime(1976, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Artem1212@gmail.com",
                            InstagramUrl = "Artem1212",
                            Name = "Artem"
                        },
                        new
                        {
                            Id = 4,
                            DeteofBirth = new DateTime(1985, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Andrey1995@gmail.com",
                            InstagramUrl = "Andrey1995",
                            Name = "Andrey"
                        },
                        new
                        {
                            Id = 5,
                            DeteofBirth = new DateTime(1999, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Anna1999@gmail.com",
                            InstagramUrl = "Anna1412",
                            Name = "Anna"
                        });
                });

            modelBuilder.Entity("HW6_module4.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Rock"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Djaz"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Classic"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Rap"
                        });
                });

            modelBuilder.Entity("HW6_module4.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Duration")
                        .HasColumnType("float")
                        .HasColumnName("Duration");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleasedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReleasedDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 4.5,
                            GenreId = 1,
                            ReleasedDate = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lastivki"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 3.5,
                            GenreId = 5,
                            ReleasedDate = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Klever"
                        },
                        new
                        {
                            Id = 3,
                            Duration = 4.2999999999999998,
                            GenreId = 5,
                            ReleasedDate = new DateTime(2014, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tyt"
                        },
                        new
                        {
                            Id = 4,
                            Duration = 4.5,
                            GenreId = 2,
                            ReleasedDate = new DateTime(1994, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kykyshka"
                        },
                        new
                        {
                            Id = 5,
                            Duration = 3.7999999999999998,
                            GenreId = 3,
                            ReleasedDate = new DateTime(2010, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Prognoz"
                        });
                });

            modelBuilder.Entity("ArtistSong", b =>
                {
                    b.HasOne("HW6_module4.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HW6_module4.Song", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HW6_module4.Song", b =>
                {
                    b.HasOne("HW6_module4.Genre", "Genre")
                        .WithMany("Songs")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("HW6_module4.Genre", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
